version: '3.8'
services:
  fastapi-groq-app:
    build: .
    environment:
      - GROQ_API_KEY=your_api_key
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi-groq-app
